apiVersion: v1
kind: Service
metadata:
  name: microservicio-java-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 3000
  selector:
    app: microservicio-java
