name: CI

on:
  push:

jobs:

  Pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK para Maven
        uses: actions/setup-java@main
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Compilar Dependencias Maven 
        run: |
          mvn package

      - name: Test Unitarios y Reporte Cobertura
        run: |
          mvn verify

      - name: Subir Reporte JaCoCo como Artefacto
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      - name: Setup Java JDK para SonarCloud
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Analisis Sonar Cloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=sebagq \
          -Dsonar.projectKey=SebaGQ_microservicio-java-devops-foundation

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: https://sonarcloud.io
          
